### ISSUE TITLE
Project rename idea: backup-rhocs

### ISSUE THREAD

**Issue by AshtonDavis** [red-hat-storage/rhocs-backup#6]
Just because it's fun to be a little cheeky with open source project names. Since we pronounce "rhocs" as "rocks", a new name "backup-rhocs" would read like "Backup Rocks", which of course it does!

**Comment by luisrico** [comment]
> Just because it's fun to be a little cheeky with open source project names. Since we pronounce "rhocs" as "rocks", a new name "backup-rhocs" would read like "Backup Rocks", which of course it does!

Thanks for suggestion, despite it's funny, we have already published blog using this name order.
